### ISSUE TITLE
HBGShop does not work anymore

### ISSUE THREAD

**Issue by Bahamut** [coniventia/tinfoilmod-releases#7]
Probably the spoof is not working anymore?
[FakeSentVersion = Spoofs the Tinfoil version sent to the locations.]
Actual is 5.10.

The other parts of the app seem to work fine tho, even with other shops.

**Comment by coniventia** [comment]
The private keys in the blob (used for location data encryption) have changed. /hbg/Shop seems to be using 5.10 keys.
This cannot be spoofed.
